### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by tyvdh** [astroband/astrologer#6]
Getting this issue a lot when exporting. Curious what it stems from and how it might be avoided.

```
$ astrologer export
Exporting ledgers from 11000 to 603456 total 592457
   2% |██                                                                                                  | (11850/592457) [8m7s:6h38m0s]panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1507cc0]

goroutine 23 [running]:
github.com/astroband/astrologer/es.newPathPaymentResult(0x0, 0xc00037be50, 0x0, 0xc00049e200)
	/Users/tyler/go/src/github.com/astroband/astrologer/es/operation_result.go:63 +0x270
github.com/astroband/astrologer/es.AppendResult(0xc00049e200, 0xc000300d70)
	/Users/tyler/go/src/github.com/astroband/astrologer/es/operation_result.go:21 +0x10d
github.com/astroband/astrologer/es.MakeBulk(0xc0006f3a40, 0x40, 0xc0006f3a80, 0x40, 0xc0006f3ac0, 0x40, 0x6cfc, 0x5cc278a1, 0x865e98230000000a, 0xc49a694a36f26f1f, ...)
	/Users/tyler/go/src/github.com/astroband/astrologer/es/make_bulk.go:36 +0x12c
github.com/astroband/astrologer/commands.exportBlock(0x152)
	/Users/tyler/go/src/github.com/astroband/astrologer/commands/export.go:52 +0x1cb
github.com/astroband/astrologer/commands.Export.func1()
	/Users/tyler/go/src/github.com/astroband/astrologer/commands/export.go:36 +0x2a
github.com/gammazero/workerpool.startWorker.func1(0xc000094120, 0xc0000b4c00)
	/Users/tyler/go/src/github.com/gammazero/workerpool/workerpool.go:253 +0x68
created by github.com/gammazero/workerpool.startWorker
	/Users/tyler/go/src/github.com/gammazero/workerpool/workerpool.go:238 +0x49
```

**Comment by tyvdh** [comment]
https://stackoverflow.com/questions/16280176/go-panic-runtime-error-invalid-memory-address-or-nil-pointer-dereference

**Comment by tyvdh** [comment]
Don't know if it's helpful but I'm trying to sync with the testnet and it won't get past ledger `27800`

`astrologer export 27800 --batch 1`

```
Exporting ledgers from 27800 to 604207 total 576408
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1507cc0]

goroutine 66 [running]:
github.com/astroband/astrologer/es.newPathPaymentResult(0x0, 0xc0028f3680, 0x0, 0xc0031b8400)
	/Users/tyler/go/src/github.com/astroband/astrologer/es/operation_result.go:63 +0x270
github.com/astroband/astrologer/es.AppendResult(0xc0031b8400, 0xc000144270)
	/Users/tyler/go/src/github.com/astroband/astrologer/es/operation_result.go:21 +0x10d
github.com/astroband/astrologer/es.MakeBulk(0xc0032adfc0, 0x40, 0xc00338e000, 0x40, 0xc00338e040, 0x40, 0x6cfc, 0x5cc278a1, 0x865e98230000000a, 0xc49a694a36f26f1f, ...)
	/Users/tyler/go/src/github.com/astroband/astrologer/es/make_bulk.go:36 +0x12c
github.com/astroband/astrologer/commands.exportBlock(0x64)
	/Users/tyler/go/src/github.com/astroband/astrologer/commands/export.go:52 +0x1cb
github.com/astroband/astrologer/commands.Export.func1()
	/Users/tyler/go/src/github.com/astroband/astrologer/commands/export.go:36 +0x2a
github.com/gammazero/workerpool.startWorker.func1(0xc00018c720, 0xc000164420)
	/Users/tyler/go/src/github.com/gammazero/workerpool/workerpool.go:253 +0x68
created by github.com/gammazero/workerpool.startWorker
	/Users/tyler/go/src/github.com/gammazero/workerpool/workerpool.go:238 +0x49
```

**Comment by charlie-wasp** [comment]
Thank you for the report, I'm on investigation 🕵 Quick thought: you try to ingest ledgers from the dawn of Stellar network, maybe XDR format has been changed since that, and there were no claimed offers in path payment operation result
